Bump rails to 7.1.4
Something changed in `delegate_missing_to`.
Minitest tests failed with errors like this:

Error:
Import::SessionAncillaryTest#test_#buffered?_true:
NoMethodError: unmocked method :nil?, expected one of [:buffer]
    app/models/import/session_ancillary.rb:7:in `buffered?'
    test/models/import/session_ancillary_test.rb:26:in `block in <class:SessionAncillaryTest>'